### ISSUE TITLE
Keyless array of object parse

### ISSUE THREAD

**Issue by tmoitie** [hapijs/qs#103]
Parsing a query string like this: `tags[][name]=Red&tags[][id]=1&tags[][name]=Blue&tags[][id]=2`

Returns `{ tags: [ { name: ['Red', 'Blue'], id: [1, 2] } ] }`

When I was expecting `{tags: [{name: 'Red', id: 1}, {name: 'Blue', id: 2}]}`, which is the object that was passed through `qs.stringify(…, { arrayFormat: 'brackets' })`

**Comment by nlf** [comment]
by passing `'brackets'` as your arrayFormat, you're telling qs to be more ambiguous with how your object is stringified, which is why you get a result you don't expect. the default behavior of stringify is to include array indices, which would yield a string like

`tags[0][name]=Red&tags[0][id]=1&tags[1][name]=Blue&tags[1][id]=2`

which you'll find parses exactly how you want it to. without the array indices it's literally impossible for qs to guess what properties belong in what array members, so it just puts them all together.
