### ISSUE TITLE
ES6 style changes and node v4

### ISSUE THREAD

**Issue by hueniverse** [hapijs/qs#124]
The hapi world is moving to only support node >= 4.0. This module is part of that world. I want to make sure the express community is aware of it as they are a significant user of this module. Also, this will affect use in the browser in pre-ES6 versions.

@dougwilson

**Comment by dougwilson** [comment]
Hi @hueniverse , that sounds fine to me. We have no timeline to drop 0.10, unfortunately, and so we'll likely just fork this module for our ecosystems, if it becomes necessary. Likely, we'll sit on an old version unless there is some security issue :)

**Comment by hueniverse** [comment]
If there are security issues we'll publish a 5.x patch since hapi 9.x will need it too.

**Comment by dougwilson** [comment]
Even better :) Don't let us hold ya back ;)

**Comment by taion** [comment]
This is fairly unfriendly to people using this library v. e.g. browserify or webpack.

Have you considered still including a transpiled build in the npm package, then pointing the `"browser"` key in `package.json` to that?

**Comment by Marsup** [comment]
This is fairly unfriendly to force maintainers to also maintain builds while you can make it yourself.

**Comment by taion** [comment]
Aren't you already maintaining a browser package at `dist/qs.js`? It looks like it hasn't been updated for 6.x yet and is still on 5.2.0, but you're going to have to pull in babelify to produce an updated browser bundle for 6.x that will actually run in browsers.

Either way, the reason this comes up is because in general when producing browser bundles, best practice is to exclude anything from `node_modules` for transpilation to avoid any dependencies on how exactly people are configuring Babel.

I like the approach you're taking with moving to use Node's ES6-supported features for Node code. It wouldn't be the end of the world if you dropped browser support in this library entirely, but right now you're actually shipping broken/outdated browser support via the distributed bundle, and would need to bring in Babel yourself to properly ship that bundle.

**Comment by nlf** [comment]
You're right it is silly that we have an outdated browser build, but that's also why I have an open issue to remove that build. If you'd like to see browser support continued here, I'd be happy to hand the module over to you

**Comment by taion** [comment]
I just saw that issue, sorry.

I have a few more JS packages than I can get around to maintaining at the moment, unfortunately, but I'd be happy to contribute a PR that fixes the browser build if that's something you're interested in.

**Comment by nlf** [comment]
I'm more inclined to accept a PR removing all the current browser support

**Comment by taion** [comment]
I see - thanks.

**Comment by evantahler** [comment]
Thanks for keeping `v5.x` around, and offering to publish security patches if they come up.  [Actionhero](https://github.com/evantahler/actionhero) just switched to this library as well, and it's great!   That said, we'll still be supporting node v0.10+ for another few months...

**Comment by mmahalwy** [comment]
I am having problems with this library breaking my tests cause I don't intend to bundle node_modules...

**Comment by ljharb** [comment]
It's very sad to have a module that is published in such a way that it requires transpilation to be used in a browser or older node environment. Why is it difficult to add a babel prepublish step?

**Comment by devinivy** [comment]
@ljharb feel free to check-out the discussion around this at https://github.com/hapijs/contrib/issues/67

**Comment by ljharb** [comment]
Thanks, commented https://github.com/hapijs/contrib/issues/67#issuecomment-166439706

**Comment by hueniverse** [comment]
use version 5. I'm locking this issue
