### ISSUE TITLE
Should export ES5-compatible for npm, otherwise babel transform is required externally

### ISSUE THREAD

**Issue by sompylasar** [hapijs/qs#139]
The ES2015-rewritten 6.0.0 has issues when using via webpack. Usually, babel transform is only applied to the app code, and the `node_modules` directory is excluded entirely. This does not work with 6.0.0 compared to ES5-compatible 5.2.0 -- webpack bundles the ES2015 code of the `node_modules/qs` right into the output, which then breaks the uglify step.

Please provide ES5-compatible build without browserify and point `package.json`'s `main` to it.

This can be done in the `prepublish` step. Look [how it's implemented](https://github.com/rackt/redux-router/blob/master/package.json).

Related: #128, #129, #108.

**Comment by hueniverse** [comment]
Just use the previous version for now. They are the same.

**Comment by sompylasar** [comment]
@hueniverse yes, I do this for now.

**Comment by bdefore** [comment]
i ran into this issue while updating my dependencies and saw the latest was 6.0.0 ... unfortunately this caused me to see the error `SyntaxError: let is a reserved identifier` and it was due to the issue @sompylasar describes. this should probably not be published in npm right now.

**Comment by hueniverse** [comment]
I suggest you learn how semver works and don't upgrade to a new major version without understanding what broke.

**Comment by bdefore** [comment]
@hueniverse i am aware of how semver works, thank you. thought you might want to know that there's more than one person that would like to use `qs` latest with other their other ES5 transpiled libraries.

**Comment by arb** [comment]
You can also add the path to qs in your array of included files for the babel transformer. Then you could exclude all of the other node_modules, but include qs.

**Comment by zerkms** [comment]
@arb 

> You can also add the path to qs in your array of included files for the babel transformer

how would one do that actually? If `node_modules` is excluded using `exclude` parameter - you cannot include anything from it.

**Comment by arb** [comment]
When you are setting up the loader, if you are excluding "node_modules", there is also an `include` option where you can pass an array of values. Add the path to QS into that array. (This is just speculating as I haven't done this, but I think that should work.)

```js
module: {
  loaders: [
    {
      test: /\.js?$/,
      exclude: /node_modules/,
      include: [
        'path/to/your/app',
        'node_modules/qs'
      ]
      loader: 'babel',
      query: {
        presets: ['es2015']
      }
    }
  ]
}
```

Something along those lines. You'll have to play around with the include paths but that is the general gist of it.

**Comment by sompylasar** [comment]
There are certainly workarounds but this does not actually resolve the
issue.

**Comment by nlf** [comment]
There is no way to resolve this because there is no issue. This module is ES6 now. If you need ES5, either use an older version or configure your transpiler to deal with it for you.

**Comment by sompylasar** [comment]
https://github.com/nodejs/help/issues/8

**Comment by sompylasar** [comment]
http://jonnyreeves.co.uk/2015/babel-npm/

**Comment by nlf** [comment]
I'm aware of the many methods available for maintaining an ES5 version of this module. I have no interest in doing so. If you really want an ES5 version, build and publish one. I'm happy to link to it from here.

**Comment by sompylasar** [comment]
I see. Good luck then.

**Comment by zerkms** [comment]
@arb that was my exact point: if a path is in `exclude` - there is no way to make it loaded. That's what `exclude` is for - to exclude.

**Comment by Marsup** [comment]
Come on, it's a regex, It's not that hard to exclude `/node_modules\/(?!qs)/`...

I stand with @nlf, it's your problem if you want to take it into an ES5-only environment, this module explicitly says it uses node 4+ and YOU have ways to deal with it.

**Comment by dantman** [comment]
I'd like to state that in some cases "configure your transpiler to deal with it for you" is actually a ridiculous suggestion.

I'm using browserify, but:
* `qs` hasn't declared something like `"browserify": {"transform": [["babelify", {"presets": ["es2015"]}]]}` so browserify doesn't work out of the box and I can't add this to the `qs` package myself.
* "linking" to a 3rd party published browser build won't change anything since browserify wouldn't pick up on it, it's not actually part of the module.
* The ["other"](https://github.com/babel/babelify#why-arent-files-in-node_modules-being-transformed) option of configuring babelify as a global transform, doesn't actually work. Or rather, whether it works or not depends entirely on every other random module you depend on.
   * When you `ignore` files, that doesn't actually tell the transform to go and ignore entire modules. It's a babel level option and subject to other babel level options defined elsewhere. So babel still goes through the tree and parses other options like those in .babelrc files belonging to every single module you depend on.
  * This sort of works... up until you hit one of the modules that is transpiled during prepublish using babel@5, and then this happens `Unhandled rejection ReferenceError: [BABEL] /.../node_modules/react-leaflet/lib/index.js: Unknown option: /.../node_modules/react-leaflet/.babelrc.optional while parsing file: /.../node_modules/react-leaflet/lib/index.js`

**Comment by SteveALee** [comment]
It seems to me that as this is an official hapi module there should be an official hapi policy in place for module dependencies.

My vote is make it work for the widest possible audience. At least until ES5 is way down the long tail.

**Comment by nlf** [comment]
we have a discussion along those lines going [here](https://github.com/hapijs/contrib/issues/67)

**Comment by ericclemmons** [comment]
Had the same problem & spent more time researching it than it took to fix it with webpack:

```js
module: {
  loaders: [
        {
          exclude: /node_modules/,
          loader: "babel-loader",
          test: /\.js$/,
        },
        {
          include: /node_modules\/qs/),
          loader: "babel-loader",
          test: /\.js$/,
        },
    ],
  }
}
```

Happy copy-pasting!

**Comment by necolas** [comment]
> come on, it's a regex, It's not that hard to exclude /node_modules\/(?!qs)/...
> I stand with @nlf, it's your problem if you want to take it into an ES5-only environment, this module explicitly says it uses node 4+ and YOU have ways to deal with it.

Well, this module is meant to work in browsers, so forcing every dependent package or app to make a special case for this one untranspiled package is spreading the burden and confusion.

**Comment by arb** [comment]
I think you could also replace `include: /node_modules\/qs/)` with `include: require.resolve('qs')` as well which would be a little clearer what you're trying to do.
