### ISSUE TITLE
Add option to disable "Transform dot notation to bracket notation"

### ISSUE THREAD

**Issue by dougwilson** [hapijs/qs#89]
Can we get an option to disable the new "Transform dot notation to bracket notation" functionality? We would like to keep our code base current with the latest version of this module, but we do NOT want to allow users to submit this new syntax to our API. Since this is done just through a `.replace`, it seems like it would be trivial to add a switch that would skip that transformation (but it can still be enabled by default, of course).

**Comment by nlf** [comment]
Absolutely. I'll get that added tonight or tomorrow.

Sent from my iPhone

On May 25, 2015, at 11:08 AM, Douglas Christopher Wilson <
notifications@github.com> wrote:

Can we get an option to disable the new "Transform dot notation to bracket
notation" functionality? We would like to keep our code base current with
the latest version of this module, but we do NOT want to allow users to
submit this new syntax to our API. Since this is done just through a
.replace, it seems like it would be trivial to add a switch that would skip
that transformation (but it can still be enabled by default, of course).

—
Reply to this email directly or view it on GitHub
<https://github.com/hapijs/qs/issues/89>.

**Comment by dougwilson** [comment]
Thanks! Though I don't see mention of the option in the Readme?

**Comment by nlf** [comment]
it's in the readme now courtesy of #93
